server:
  port: 8080
  
spring:
  profiles:
    active: "local"
  main:
    banner-mode: "off"
    
---

spring:
  profiles: dev
  datasource:
        url: jdbc:mysql://localhost:3306/isbg?serverTimezone=UTC
        username: root
        password: hola123
        driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none      
      
  main:
    banner-mode: "off"
    
---    
    
spring:
  profiles: local
  datasource:
        url: jdbc:mysql://localhost:3306/clip?serverTimezone=UTC
        username: root
        password: hola123
        driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none      
      
  main:
    banner-mode: "off"
